dummy: abc
libraryDBConfig:
  driverClass: org.postgresql.Driver
  user: postgres
  password: pass
  url: jdbc:postgresql://localhost:5432/table_affermare
  validationQuery: select 1
  initialSize: 2
  minSize: 2
  maxSize: 8
